### ISSUE TITLE
viewport kicked after showing/hiding nodes

### ISSUE THREAD

**Issue by mochaholic** [cytoscape/cytoscape.js#932]
This is an issue in the unstable version --the master seems to work fine. 
I notice that using the unstable branch, every time I call show()/hide() or even select()/unselect() on some nodes, the entire graph is kicked to the right as if panned and zoomed. (animate is disabled). 
This seems to be an issue with redrawing. I tried cy.batch() to avoid any unnecessary redrawing with no luck.
(I am using the unstable version because of the word wrapping feature since I need to show multi-line labels.)

**Comment by maxkfranz** [comment]
Are you using the latest unstable?  That was a bug in previous versions but should be fixed now.

**Comment by mochaholic** [comment]
Yes. I just tried using the most recent unstable from this morning and the problem is still there.

**Comment by maxkfranz** [comment]
This should disable the buffer that causes the issue completely, though at the constant ratio of 1 used in recent versions this shouldn't be a problem anyway.  This might help, but it's worthwhile anyway in that it's a slight optimisation.  I can't reproduce your issue at all, except on older versions.

Try the snapshot, maybe you're having an issue building the latest unstable?
http://js.cytoscape.org/download/cytoscape.js-snapshot-746167d48b-1431365694771.zip

Closing for now
